### ISSUE TITLE
migration to graph classification tasks

### ISSUE THREAD

**Issue by ScottLiao920** [chisam0217/Graph-Universal-Attack#1]
hi chisam, congrats for coming up with this very first work on graph universal adversarial attack. I've noticed that you've limited your algorithm in node classification tasks, but I think your algorithm can be migrated to graph level with some minor modifications. 
Could u pls do the migrations?

**Comment by chisam0217** [comment]
Hi, thanks for being interested in our work. However, in my opinion, such a universal patch in our paper can hardly be directly applied to graph classification tasks.  The idea of attacking with a universal adversarial patch is feasible for tasks that only involve a single graph, e.g., node classification and link prediction. For graph classification tasks that involve various graphs, it is difficult to connect different graphs with a universal patch in a proper and efficient manner, due to different graph sizes.
